version: "3.7"

services:
  web:
    build: .
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
      - db
      - ui
  ui:
    image: covid-hackathon-ui:latest
    ports:
      - 5001:80
    environment:
      - "API_URL=http://web:5000"
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=help_directory
    restart: always
    networks:
      - default
volumes:
  postgres_data:
