version: "3.7"

services:
  web:
    build: .
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5003:5000
    depends_on:
      - db
      - ui
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8

  migration-upgrade:
    image: covid-hackathon-migration:latest
    depends_on:
      - db
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: python3 migrate.py db upgrade

  migration-run:
    image: covid-hackathon-migration:latest
    depends_on:
      - db
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: python3 migrate.py db migrate

  ui:
    image: covid-hackathon-ui:latest
    ports:
      - 5051:80
    environment:
      - "API_URL=http://web:5003"
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=help_directory
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    networks:
      - default
volumes:
  postgres_data:
